apiVersion: v2
name: kramerius
description: Kramerius 7 - digital library system
type: application
version: 1.0.4
appVersion: "7.2.0"
maintainers:
  - name: Randiak Robert
    email: robert.randiak@mzk.cz
