{{- if .Values.admin.enabled }}

{{- if not .Values.admin.host }}
{{ fail "admin.host is required when admin.enabled is true" }}
{{- end }}

{{- if not .Values.admin.host.name }}
{{ fail "admin.host.name is required when admin.enabled is true" }}
{{- end }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kramerius-admin-client
  labels:
{{ include "kramerius-admin-client.labels" . | indent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/real-ip-header: X-Forwarded-For
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.admin.host.name }}
      secretName: kramerius-admin
  rules:
    - host: {{ .Values.admin.host.name }}
      http:
        paths:
          - path: {{ .Values.admin.host.path | default "/" }}
            pathType: Prefix
            backend:
              service:
                name: kramerius-admin-client
                port:
                  name: http
{{- end }}
