{{- if .Values.admin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kramerius-admin-client
  labels:
{{ include "kramerius-admin-client.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
{{ include "kramerius-admin-client.labels" . | indent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.admin.service.port }}
      targetPort: {{ .Values.admin.container.port }}
{{- end }}
