apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-openresty-nginx
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kramerius.labels" . | nindent 4 }}
    {{- include "kramerius.gateway.matchLabels" . | nindent 4 }}
data:
  nginx.conf: |
{{ tpl (.Files.Get "files/gateway/nginx.conf") . | nindent 4 }}

