apiVersion: v1
entries:
  kramerius:
  - apiVersion: v2
    appVersion: 7.1.0-rc1
    created: "2025-06-02T15:40:25.926613302Z"
    description: Helm chart for orchestrating multi-instance Kramerius
    digest: 7bec585b5414814bca6e29b00537afb03f7efa19be1d307ce8d0a0ab2242b4f2
    maintainers:
    - email: robert.randiak@mzk.cz
      name: Randiak Robert
    name: kramerius
    type: application
    urls:
    - https://rrandiak.github.io/kramerius-helm-chart/charts/kramerius-0.1.0.tgz
    version: 0.1.0
generated: "2025-06-02T15:40:25.924847916Z"
