{{- range .Values.instances }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kramerius-{{ .name }}-tomcat-config
data:
  {{- if .kramerius.properties.context }}
  context.xml: |-
{{ .Files.Get .kramerius.properties.context | indent 4 }}
  {{- end }}

  {{- if .kramerius.properties.server }}
  server.xml: |-
{{ .Files.Get .kramerius.properties.server | indent 4 }}
  {{- end }}

  {{- if .kramerius.properties.logging }}
  logging.properties: |-
{{ .Files.Get .kramerius.properties.logging | indent 4 }}
  {{- end }}
{{- end }}
