{{- if eq (include "kramerius.observability.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kramerius.observability.vectorName" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kramerius.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "kramerius.observability.vectorName" . }}
    app.kubernetes.io/component: observability
data:
  vector.yaml: |
    {{- include "kramerius.observability.vectorPipeline" . | nindent 4 }}
{{- end }}
