apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
{{ include "postgres.labels" . | indent 4 }}
spec:
  clusterIP: None
  selector:
{{ include "postgres.labels" . | indent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.container.port }}
