apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.kramerius.cluster.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kramerius.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "kramerius"
  password: {{ required "cnpg.kramerius.password is required" .Values.cnpg.kramerius.password | quote }}
