apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.processManager.cluster.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kramerius.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: "process"
  password: {{ required "cnpg.processManager.password is required" .Values.cnpg.processManager.password | quote }}
