apiVersion: v1
kind: ConfigMap
metadata:
  name: kramerius-keycloak
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kramerius.labels" . | nindent 4 }}
data:
  keycloak.json: |
    {{- include "kramerius.keycloakAdapterJson" . | nindent 4 }}
