{{- range $key := list "javaagents" "import" "akubra-object-store" "akubra-datastream-store" "imageserver" "audioserver" "pdfserver" }}
{{- $st := index $.Values.storages $key }}
{{- if and (eq $st.type "pvc") (not $st.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kramerius.storagePvcName" (dict "root" $ "storageKey" $key) }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "kramerius.labels" $ | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "kramerius.storagePvcStorageClass" (dict "root" $ "storageKey" $key) | quote }}
  resources:
    requests:
      storage: {{ $st.size }}
{{- end }}
{{- end }}
