name: Package and Publish Helm Chart

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Package Helm chart and generate index
      run: |
        helm package .
        mkdir -p repo
        mv *.tgz repo/
        helm repo index repo --url https://rrandiak.github.io/kramerius-helm-chart/

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo
        publish_branch: gh-pages
