name: Package and Publish Helm Chart

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.12.0

    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages

    - name: Package Helm chart and merge with existing packages
      run: |
        helm package .
        mv *.tgz gh-pages/
        helm repo index gh-pages --url https://rrandiak.github.io/kramerius-helm-chart/

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages
